### ISSUE TITLE
Different/Private GitHub handle on Installation 

### ISSUE THREAD

**Issue by toramanemre** [ipa-lab/docs.hackingbuddy#4]
On installation page there is different or private GitHub URL than ipa-lab. 

<img width="1144" alt="image" src="https://github.com/ipa-lab/docs.hackingbuddy/assets/24626967/29fecc45-39d8-4f60-8b98-8290e10ba22a">

**Comment by andreashappe** [comment]
Great catch! That was my original repository before I moved the Project to github.com/ipa-labs. will fix (:
